---
- hosts: docker
  tasks:
  - name: stop existing container
    command: docker stop regapp-server
    ignore_errors: yes

  - name: remove existing container
    command: docker rm regapp-server
    ignore_errors: yes

  - name: remove image
    command: docker rmi kundith/regapp:latest
    ignore_errors: yes

  - name: create container from the docker image pushed to docker hub
    command : docker run -d --name regapp-server -p 8082:8080 kundith/regapp:latest
